import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const siteRoot = path.resolve(scriptDir, "..");
const appDir = path.join(siteRoot, "app");
const outputPath = path.join(siteRoot, "lib", "generated-sitemap.ts");
const siteUrl = process.env.NTE_SITE_URL ?? "https://nte-tools.com";

const ignoredSegments = new Set(["api"]);

const pages = collectPages(appDir)
  .map((filePath) => {
    const route = pageFileToRoute(filePath);
    return {
      route,
      lastModified: lastModifiedFor(filePath),
      priority: priorityFor(route),
      changeFrequency: changeFrequencyFor(route),
    };
  })
  .sort((a, b) => routeWeight(a.route) - routeWeight(b.route) || a.route.localeCompare(b.route));

const source = `// This file is generated by scripts/generate-sitemap.mjs.
// Do not edit by hand.

export const SITE_URL = ${JSON.stringify(siteUrl)};

export const SITE_ROUTES = ${JSON.stringify(pages, null, 2)} as const;
`;

fs.writeFileSync(outputPath, source, "utf8");
console.log(`Generated ${path.relative(siteRoot, outputPath)} with ${pages.length} routes.`);

function collectPages(dir) {
  const pages = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (entry.name.startsWith("_")) continue;
      if (entry.name.startsWith("(") && entry.name.endsWith(")")) {
        pages.push(...collectPages(fullPath));
        continue;
      }
      if (entry.name.startsWith("[") || ignoredSegments.has(entry.name)) continue;
      pages.push(...collectPages(fullPath));
      continue;
    }
    if (entry.isFile() && entry.name === "page.tsx") pages.push(fullPath);
  }
  return pages;
}

function pageFileToRoute(filePath) {
  const relative = path.relative(appDir, path.dirname(filePath));
  if (!relative || relative === ".") return "/";
  const segments = relative
    .split(path.sep)
    .filter((segment) => segment && !(segment.startsWith("(") && segment.endsWith(")")));
  return `/${segments.join("/")}`;
}

function lastModifiedFor(filePath) {
  try {
    const value = execFileSync("git", ["log", "-1", "--format=%cI", "--", filePath], {
      cwd: siteRoot,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
    if (value) return value.slice(0, 10);
  } catch {
    // Fall back to filesystem mtime when git metadata is unavailable, such as
    // release-folder-only checks.
  }
  return fs.statSync(filePath).mtime.toISOString().slice(0, 10);
}

function priorityFor(route) {
  if (route === "/") return 1;
  if (route === "/buildcard") return 0.9;
  return 0.4;
}

function changeFrequencyFor(route) {
  if (route === "/" || route === "/buildcard") return "weekly";
  return "monthly";
}

function routeWeight(route) {
  if (route === "/") return 0;
  if (route === "/buildcard") return 1;
  return 10;
}
